Repository secureCodeBox/securecodebox.github.io, pull requests merged in 2020-08, with the labels that each got.

#13 Refactored the integrations page layout
  gatsby-config.js
  src/components/IntegrationCard.js
  src/pages/integrations/index.js
  src/scss/components/_integration-card.scss
  src/scss/style.scss
  src/templates/integration.js
  static/images/undraw_mind_map_cwng.svg
  static/images/undraw_product_iteration_kjok.svg
  static/images/undraw_version_control_9bpv.svg
  static/integrationIcons/Cascading Scans.svg
  static/integrationIcons/Cascading Scans2.svg
  static/integrationIcons/Generic WebHook.svg
  static/integrationIcons/MS Teams WebHook.svg
  static/integrationIcons/Slack WebHook.svg
  static/integrationIcons/Update Field.svg
  static/integrationIcons/kubeaudit.svg
Labels: documentation

#12 Doc integration examples
  gatsby-node.js
  src/components/ScannerExamples.js
  src/pages/integrations/index.js
  src/templates/integration.js
  src/templates/scannerExamples.js
Labels: documentation

#9 Update website for v2
  README.md
  gatsby-config.js
  gatsby-node.js
  package-lock.json
  package.json
  src/components/BetaAlert.js
  src/components/Footer.js
  src/components/IntegrationCard.js
  src/components/Layout.js
  src/components/MenuMobile.js
  src/components/ScannerExamples.js
  src/pages/index.js
  src/pages/integrations/index.js
  src/scss/components/_beta-alert.scss
  src/scss/components/_feature.scss
  src/scss/components/_footer.scss
  src/scss/components/_integration-card.scss
  src/scss/pages/_home.scss
  src/scss/style.scss
  src/templates/integration.js
  static/images/undraw_mind_map_cwng.svg
  static/images/undraw_product_iteration_kjok.svg
  static/images/undraw_version_control_9bpv.svg
  static/integrationIcons/Cascading Scans.svg
  static/integrationIcons/Cascading Scans2.svg
  static/integrationIcons/Generic WebHook.svg
  static/integrationIcons/MS Teams WebHook.svg
  static/integrationIcons/Slack WebHook.svg
  static/integrationIcons/Trivy.svg
  static/integrationIcons/Update Field.svg
  static/integrationIcons/kube-hunter.svg
  static/integrationIcons/kubeaudit.svg
Labels: documentation

#15 add condition to render examples
  src/templates/integration.js
Labels: enhancement

#14 Bugfix/v2 integrations sidemenu
  package-lock.json
  package.json
  src/components/MenuMobile.js
  src/components/ScannerExamples.js
  src/components/Sidebar.js
  src/scss/components/_sidebar.scss
  src/templates/integration.js
Labels: bug

#17 Add Highlighting to Code Blocks
  gatsby-config.js
  gatsby-node.js
  package-lock.json
  package.json
  src/components/ScannerExamples.js
  src/scss/pages/integrations/_integration.scss
  src/styles/global.css
  src/templates/integration.js
Labels: enhancement

#18 Feature/collapsible component
  package-lock.json
  package.json
  src/components/Collapsible.js
  src/components/ScannerExamples.js
  src/components/Sidebar.js
  src/scss/components/_collapsible.scss
  src/scss/components/_sidebar.scss
  src/scss/style.scss
Labels: enhancement
