Repository secureCodeBox/securecodebox.github.io, pull requests merged in 2020-09, with the labels that each got.

#19 Add info page about telemetry data collection
  src/pages/telemetry/index.js
  src/pages/telemetry/telemetry.md
Labels: documentation

#16 Feature/rework navigation
  gatsby-config.js
  gatsby-node.js
  package-lock.json
  package.json
  src/components/Menu.js
  src/images/GetStarted.png
  src/images/Integrations.png
  src/images/LandingPage.png
  src/pages/docs/index.js
  src/pages/docs/placeholder.md
  src/pages/getStarted/index.js
  src/pages/index.js
  src/pages/integrations/index.js
  src/pages/integrations/persistence-provider/defectDojo.md
  src/pages/integrations/persistence-provider/elasticsearch.md
  src/scss/components/_beta-alert.scss
  src/scss/components/_footer.scss
  src/scss/components/_header.scss
  src/scss/components/_intro.scss
  src/scss/components/_main-menu.scss
  src/scss/pages/_home.scss
  src/scss/pages/getStarted/_doc.scss
  src/scss/pages/getStarted/_page-getStarted.scss
  src/scss/pages/integrations/_page-integrations.scss
  src/scss/style.scss
  src/templates/doc.js
  src/templates/docs.js
  src/templates/getStarted.js
  static/features/Developer Guide.svg
  static/features/User Guide.svg
Labels: enhancement

#20 Frontpage rework
  README.md
  package-lock.json
  package.json
  src/components/Footer.js
  src/data/features.json
  src/images/approved.svg
  src/images/close.svg
  src/images/not approved.svg
  src/images/tick.svg
  src/pages/index.js
  src/scss/components/_feature.scss
  src/scss/pages/_home.scss
  static/features/code.svg
  static/features/content.svg
  static/features/graph.svg
  static/features/quick.svg
Labels: Website
